# Generated by Django 3.2.6 on 2021-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='surname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
