# Generated by Django 3.2.6 on 2021-09-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210924_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code_postal', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.wilaya'),
        ),
    ]
