# Generated by Django 3.2.6 on 2021-09-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210924_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Api.student'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='Departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.departement'),
        ),
    ]
