# Generated by Django 3.2.6 on 2021-09-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20210924_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.professor'),
        ),
    ]
