# Generated by Django 3.2.6 on 2021-09-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20210924_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='professor',
        ),
    ]
